---
roles:
  - src: https://github.com/NettistaNet/ansible-role-nn-base
  - src: https://github.com/githubixx/ansible-role-harden-linux
  - src: https://github.com/githubixx/ansible-role-wireguard
  - src: https://github.com/NettistaNet/ansible-role-ha-proxy
